### ISSUE TITLE
Error when using --no-sessions option and only one subject is converted

### ISSUE THREAD

**Issue by gauvinalexandre** [jmtyszka/bidskit#118]
When running the command `bidskit --no-sessions` , I get the following error:
```
Traceback (most recent call last):
  File "/home/algo/Work/python-venv/neuro/bin/bidskit", line 8, in <module>
    sys.exit(main())
  File "/home/algo/Work/python-venv/neuro/lib/python3.10/site-packages/bidskit/__main__.py", line 306, in main
    ses_clean,
UnboundLocalError: local variable 'ses_clean' referenced before assignment
```

I have no problem running the default command without `--no-sessions` with this particular file tree:
```
dataset
├── sourcedata
│   ├── SUBJECT1
│   │   └── first
│   │       ├── DICOM
│   │       │   ├── IM_0001
│   │       │   ├── IM_0002
│   │       │   ├── ...
│   │       │   └── XX_0190
│   │       └── DICOMDIR
│   ├── SUBJECT2
│   │   └── first
│   │       ├── DICOM
│   │       │   ├── IM_0001
│   │       │   ├── IM_0002
│   │       │   ├── ...
│   │       │   └── XX_0190
│   │       └── DICOMDIR
│   ├── ...
│   └── SUBJECT9
│       └── first
│           ├── DICOM
│           │   ├── IM_0002
│           │   ├── IM_0003
│           │   ├── ...
│           │   └── XX_0190
│           └── DICOMDIR
```

**Desktop:**
 - OS: Ubuntu 22.04
 - BIDSKIT 2023.1.26 (from branch master)

**Comment by jmtyszka** [comment]
Latest version (2023.2.16) should fix this. Let me know.

**Comment by gauvinalexandre** [comment]
Hi Mike! It seems to work. Thank you!
