### ISSUE TITLE
Unable to run bidskit - "TypeError: Expected maxsize to be an integer or None"

### ISSUE THREAD

**Issue by ruben-stanford** [jmtyszka/bidskit#129]
**Describe the bug**
Using Python 3.6, 3.9, and 3.12.1, I have not been able to use `bidskit` (installed through pip). Any usage of the module gives the error, "TypeError: Expected maxsize to be an integer or None" (from BIDS validator).

**To Reproduce**
Use `bidskit`

**Screenshots**

```bash
ruben1@ $ bidskit 
/home/users/ruben1/.local/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.17) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported
 version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/users/ruben1/.local/bin/bidskit", line 7, in <module>
    from bidskit.__main__ import main
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bidskit/__main__.py", line 42, in <module>
    import bidskit.translate as btr
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bidskit/translate.py", line 31, in <module>
    import bids
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids/__init__.py", line 2, in <module>
    from .layout import BIDSLayout, BIDSLayoutIndexer
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids/layout/__init__.py", line 1, in <module>
    from .layout import BIDSLayout, Query
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids/layout/layout.py", line 15, in <module>
    from bids_validator import BIDSValidator
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids_validator/__init__.py", line 2, in <module>
    from .bids_validator import BIDSValidator
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids_validator/bids_validator.py", line 8, in <module>
    class BIDSValidator():
  File "/home/users/ruben1/.local/lib/python3.6/site-packages/bids_validator/bids_validator.py", line 124, in BIDSValidator
    @lru_cache
  File "/usr/lib64/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

```

**Desktop (please complete the following information):**
 - OS: Linux / x86_64

**Comment by jmtyszka** [comment]
You're right, it's an issue during the initialization of the bids_validator package called from the pybids initialization. As a test, can you open a python interactive shell from the command line and just import the bids package only? Does that throw an error immediately? I can't tell if you're using a virtual environment for python, but one way to work around this is to set up a python 3.9 or 3.10 virtual environment using conda or venv then pip installing bidskit (or just pybids to start with) into this virtual environment and seeing if that fixes the initialization issue. Let me know - happy to continue debugging this with you.

**Comment by ruben-stanford** [comment]
Hey @jmtyszka,

Thanks for the quick reply — using a Python 3.9 virtual environments seems to have worked.
