### ISSUE TITLE
Docker build . fails in pybids install

### ISSUE THREAD

**Issue by dmd** [jmtyszka/bidskit#66]
```
Installed /usr/local/lib/python3.5/dist-packages/pybids-0.10.0-py3.5.egg
Searching for numpy>=1.15.2
Reading https://pypi.python.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/21/94/5d48401d922ad494399f74a973445d831c888ef0cd9437a4276d8a63cfe5/numpy-1.18.0rc1.zip#sha256=7b0b915190cf60e691c17147f5d955e273d4c482b795a7bb168ad4a2fe2fb180
Best match: numpy 1.18.0rc1
Processing numpy-1.18.0rc1.zip
Writing /tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.cfg
Running numpy-1.18.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sxux54o6/numpy-1.18.0rc1/egg-dist-tmp-z1qc6e0y
Processing numpy/random/_bounded_integers.pxd.in
Processing numpy/random/_mt19937.pyx
[91mTraceback (most recent call last):
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 61, in process_pyx
    from Cython.Compiler.Version import version as cython_version
ImportError: No module named 'Cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 238, in <module>
    main()
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 234, in main
    find_process_files(root_dir)
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 225, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 191, in process
    processor_function(fromfile, tofile)
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/tools/cythonize.py", line 66, in process_pyx
    raise OSError('Cython needs to be installed in Python as a module')
OSError: Cython needs to be installed in Python as a module
[0m[91mRunning from numpy source directory.
/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
[0mCythonizing sources
[91mTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 450, in <module>
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 433, in setup_package
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 240, in generate_cython
RuntimeError: Running cythonize failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 204, in <module>
    'Source': 'https://github.com/jmtyszka/bidskit/',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 436, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 680, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 727, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 772, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1131, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 450, in <module>
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 433, in setup_package
  File "/tmp/easy_install-sxux54o6/numpy-1.18.0rc1/setup.py", line 240, in generate_cython
RuntimeError: Running cythonize failed!
[0mThe command '/bin/sh -c python3 setup.py install' returned a non-zero code: 1

```

**Comment by dmd** [comment]
This is with `docker build .` at 3e328f82f829a638407bb1d01618ca34fa45a338

**Comment by jmtyszka** [comment]
This was a messy issue with compilation of numpy (and other packages) by setuptools under the default Ubuntu Bionic install. Modified Dockerfile to install all the major python3 packages explicitly before running setup.py to install bidskit.
